// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// IPS4o_insitu
List IPS4o_insitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_IPS4o_insitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(IPS4o_insitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// IPS4o_exsitu
List IPS4o_exsitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_IPS4o_exsitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(IPS4o_exsitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// IS4o_insitu
List IS4o_insitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_IS4o_insitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(IS4o_insitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// IS4o_exsitu
List IS4o_exsitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_IS4o_exsitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(IS4o_exsitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Learnsort_insitu
List Learnsort_insitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Learnsort_insitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Learnsort_insitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Learnsort_exsitu
List Learnsort_exsitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Learnsort_exsitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Learnsort_exsitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Pdqsort_insitu
List Pdqsort_insitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Pdqsort_insitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Pdqsort_insitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Pdqsort_exsitu
List Pdqsort_exsitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Pdqsort_exsitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Pdqsort_exsitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// PdqsortB_insitu
List PdqsortB_insitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_PdqsortB_insitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(PdqsortB_insitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// PdqsortB_exsitu
List PdqsortB_exsitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_PdqsortB_exsitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(PdqsortB_exsitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// gfxTimsort_insitu
List gfxTimsort_insitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_gfxTimsort_insitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(gfxTimsort_insitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// gfxTimsort_exsitu
List gfxTimsort_exsitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_gfxTimsort_exsitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(gfxTimsort_exsitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Peeksort_insitu
List Peeksort_insitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Peeksort_insitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Peeksort_insitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Peeksort_exsitu
List Peeksort_exsitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Peeksort_exsitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Peeksort_exsitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Powersort_insitu
List Powersort_insitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Powersort_insitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Powersort_insitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Powersort_exsitu
List Powersort_exsitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Powersort_exsitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Powersort_exsitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Powersort4_insitu
List Powersort4_insitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Powersort4_insitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Powersort4_insitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Powersort4_exsitu
List Powersort4_exsitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Powersort4_exsitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Powersort4_exsitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Powersort4s_insitu
List Powersort4s_insitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Powersort4s_insitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Powersort4s_insitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Powersort4s_exsitu
List Powersort4s_exsitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Powersort4s_exsitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Powersort4s_exsitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Skasort_insitu
List Skasort_insitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Skasort_insitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Skasort_insitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Skasort_exsitu
List Skasort_exsitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Skasort_exsitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Skasort_exsitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// ISkasort_insitu
List ISkasort_insitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_ISkasort_insitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(ISkasort_insitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// ISkasort_exsitu
List ISkasort_exsitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_ISkasort_exsitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(ISkasort_exsitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Timsort_insitu
List Timsort_insitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Timsort_insitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Timsort_insitu(orig));
    return rcpp_result_gen;
END_RCPP
}
// Timsort_exsitu
List Timsort_exsitu(NumericVector& orig);
RcppExport SEXP _greeNsort_Rcpp_Timsort_exsitu(SEXP origSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type orig(origSEXP);
    rcpp_result_gen = Rcpp::wrap(Timsort_exsitu(orig));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_greeNsort_Rcpp_IPS4o_insitu", (DL_FUNC) &_greeNsort_Rcpp_IPS4o_insitu, 1},
    {"_greeNsort_Rcpp_IPS4o_exsitu", (DL_FUNC) &_greeNsort_Rcpp_IPS4o_exsitu, 1},
    {"_greeNsort_Rcpp_IS4o_insitu", (DL_FUNC) &_greeNsort_Rcpp_IS4o_insitu, 1},
    {"_greeNsort_Rcpp_IS4o_exsitu", (DL_FUNC) &_greeNsort_Rcpp_IS4o_exsitu, 1},
    {"_greeNsort_Rcpp_Learnsort_insitu", (DL_FUNC) &_greeNsort_Rcpp_Learnsort_insitu, 1},
    {"_greeNsort_Rcpp_Learnsort_exsitu", (DL_FUNC) &_greeNsort_Rcpp_Learnsort_exsitu, 1},
    {"_greeNsort_Rcpp_Pdqsort_insitu", (DL_FUNC) &_greeNsort_Rcpp_Pdqsort_insitu, 1},
    {"_greeNsort_Rcpp_Pdqsort_exsitu", (DL_FUNC) &_greeNsort_Rcpp_Pdqsort_exsitu, 1},
    {"_greeNsort_Rcpp_PdqsortB_insitu", (DL_FUNC) &_greeNsort_Rcpp_PdqsortB_insitu, 1},
    {"_greeNsort_Rcpp_PdqsortB_exsitu", (DL_FUNC) &_greeNsort_Rcpp_PdqsortB_exsitu, 1},
    {"_greeNsort_Rcpp_gfxTimsort_insitu", (DL_FUNC) &_greeNsort_Rcpp_gfxTimsort_insitu, 1},
    {"_greeNsort_Rcpp_gfxTimsort_exsitu", (DL_FUNC) &_greeNsort_Rcpp_gfxTimsort_exsitu, 1},
    {"_greeNsort_Rcpp_Peeksort_insitu", (DL_FUNC) &_greeNsort_Rcpp_Peeksort_insitu, 1},
    {"_greeNsort_Rcpp_Peeksort_exsitu", (DL_FUNC) &_greeNsort_Rcpp_Peeksort_exsitu, 1},
    {"_greeNsort_Rcpp_Powersort_insitu", (DL_FUNC) &_greeNsort_Rcpp_Powersort_insitu, 1},
    {"_greeNsort_Rcpp_Powersort_exsitu", (DL_FUNC) &_greeNsort_Rcpp_Powersort_exsitu, 1},
    {"_greeNsort_Rcpp_Powersort4_insitu", (DL_FUNC) &_greeNsort_Rcpp_Powersort4_insitu, 1},
    {"_greeNsort_Rcpp_Powersort4_exsitu", (DL_FUNC) &_greeNsort_Rcpp_Powersort4_exsitu, 1},
    {"_greeNsort_Rcpp_Powersort4s_insitu", (DL_FUNC) &_greeNsort_Rcpp_Powersort4s_insitu, 1},
    {"_greeNsort_Rcpp_Powersort4s_exsitu", (DL_FUNC) &_greeNsort_Rcpp_Powersort4s_exsitu, 1},
    {"_greeNsort_Rcpp_Skasort_insitu", (DL_FUNC) &_greeNsort_Rcpp_Skasort_insitu, 1},
    {"_greeNsort_Rcpp_Skasort_exsitu", (DL_FUNC) &_greeNsort_Rcpp_Skasort_exsitu, 1},
    {"_greeNsort_Rcpp_ISkasort_insitu", (DL_FUNC) &_greeNsort_Rcpp_ISkasort_insitu, 1},
    {"_greeNsort_Rcpp_ISkasort_exsitu", (DL_FUNC) &_greeNsort_Rcpp_ISkasort_exsitu, 1},
    {"_greeNsort_Rcpp_Timsort_insitu", (DL_FUNC) &_greeNsort_Rcpp_Timsort_insitu, 1},
    {"_greeNsort_Rcpp_Timsort_exsitu", (DL_FUNC) &_greeNsort_Rcpp_Timsort_exsitu, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_greeNsort_Rcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
